apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubernetes-course-repo
  interval: 10m
  path: ./project
  prune: true 
  validation: client 