apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubernetes-course-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/franjurinec/kubernetes-devops-course
  ref:
    branch: master